name: Test CI
on:
  workflow_dispatch:
    inputs:
      env:
        description: "trigger"
        required: false
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test commands
        run: |
          npm ci
          npm run test:coverage
        working-directory: ./server

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        if: always()
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: ./server/coverage/lcov.info

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: ./server/coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
